feat: doca 3.2.2

diff --git a/pxe/templates/user-data b/pxe/templates/user-data
--- a/pxe/templates/user-data
+++ b/pxe/templates/user-data
@@ -1,4 +1,4 @@
-cat << \ZOF > /etc/bf.cfg
+cat <<\ZOF >/etc/bf.cfg
 
 # SFC variables
 ENABLE_BR_HBN=yes
@@ -11,81 +11,60 @@ BR_HBN_REPS={{ forge_hbn_reps }}
 BR_HBN_SFS={{ forge_hbn_sfs }}
 {% endif %}
 
+# Include `bmc_fw_update` file content
 {{ forge_bmc_fw_update }}
 
-# This function is called by install.sh script embedded in the BFB
-carbide_modify_os()
-{
-# set errexit so that if any command fails, we exit the script
-set -e
-ilog "======== Start of carbide_modify_os ============"
-ilog "$(/usr/sbin/fdisk -l)"
-ilog "$(/usr/bin/lsblk)"
-ilog "$(/usr/sbin/blkid)"
-ilog "$(/usr/bin/efibootmgr -v)"
-ilog "==================================="
-ilog "==================================="
-# move the files out of the installer and into the installed OS
-mkdir -p /mnt/opt/forge
-mv /forge-scout /mnt/opt/forge
-chmod a+x /mnt/opt/forge/forge-scout
-mv /forge-dpu.deb /mnt/opt/forge
-mv /doca_container_configs /mnt/opt/forge
-mv /doca_hbn.tar /mnt/opt/forge
+# This function is called by `bfb_modify_os()` as a part of install.sh script
+# embedded in the BFB installer
+carbide_modify_os() {
+  # Set errexit so that if any command fails, we exit the script
+  set -e
 
-#begin nvinit setup
-#this step is done in the BFB to ensure that we can always log in to the box, even if cloud-init fails.
-mkdir -p /mnt/opt/forge/debs
-for deb in /debs/*.deb; do  mv $deb /mnt/opt/forge/debs; done
+  # Use the standard BFB installer `ilog()` function to write logs
+  ilog "======== Start of carbide_modify_os ============"
+  ilog "$(/usr/sbin/fdisk -l)"
+  ilog "$(/usr/bin/lsblk)"
+  ilog "$(/usr/sbin/blkid)"
+  ilog "$(/usr/bin/efibootmgr -v)"
+  ilog "==================================="
+  ilog "==================================="
 
-mkdir -p /mnt/etc/nvssh
-chmod 0755 /mnt/etc/nvssh
-mv /nvinit_setup/etc-nvssh-nvssh-conf /mnt/etc/nvssh/nvssh.conf
-chmod 0644 /mnt/etc/nvssh/nvssh.conf
+  # Move the files out of the installer and into the installed OS
+  ilog "=== Prepare directory structure and move Forge and DOCA files"
+  local forge_path="/mnt/opt/forge"
+  local artifacts=(
+    /forge-scout
+    /forge-dpu.deb
+    /doca_container_configs
+    /doca_hbn.tar
+  )
+  mkdir -p "${forge_path}"
+  for artifact in "${artifacts[@]}"; do
+    [ -e "$artifact" ] || { ilog "WARN: $artifact does not exist"; continue; }
+    mv -v "$artifact" "${forge_path}"
+  done
+  chmod a+x "${forge_path}/forge-scout"
 
-mv /nvinit_setup/etc-sudoersd-nvssh-sudo /mnt/etc/sudoers.d/nvssh-sudo
-chmod 0600 /mnt/etc/sudoers.d/nvssh-sudo
-mv /nvinit_setup/etc-sudoersd-nvssh-sudo-nopasswd /mnt/etc/sudoers.d/nvssh-sudo-nopasswd
-chmod 0600 /mnt/etc/sudoers.d/nvssh-sudo-nopasswd
-mv /nvinit_setup/etc-nsswitch-conf /mnt/etc/nsswitch.conf
-chmod 0644 /mnt/etc/nsswitch.conf
-mv /nvinit_setup/etc-pamd-sshd /mnt/etc/pam.d/sshd
-chmod 0600 /mnt/etc/pam.d/sshd
-mv /nvinit_setup/etc-ssh-ngc-users-ca-keys-pem /mnt/etc/ssh/ngc-users-ca-keys.pem
-chmod 0644 /mnt/etc/ssh/ngc-users-ca-keys.pem
-mv /nvinit_setup/sbin-nss-exec /mnt/sbin/nss_exec
-chmod 0755 /mnt/sbin/nss_exec
-mv /nvinit_setup/usr-bin-nvssh /mnt/usr/bin/nvssh
-chmod 0755 /mnt/usr/bin/nvssh
-mv /nvinit_setup/etc-ssh-sshd-config /mnt/etc/ssh/sshd_config
-chmod 0644 /mnt/etc/ssh/sshd_config
+  local forge_path_debs="${forge_path}/debs"
+  ilog "=== Moving deb files to $forge_path_debs"
+  mkdir -p "$forge_path_debs"
+  for deb in /debs/*.deb; do
+    [ -e "$deb" ] || continue
+    mv -v "$deb" "$forge_path_debs"
+  done
 
-chroot /mnt chown root:root /etc/sudoers.d/nvssh-sudo
-chroot /mnt chown root:root /etc/sudoers.d/nvssh-sudo-nopasswd
-chroot /mnt chown root:root /etc/nsswitch.conf
-chroot /mnt chown root:root /etc/pam.d/sshd
-chroot /mnt chown root:root /etc/ssh/ngc-users-ca-keys.pem
-chroot /mnt chown root:root /sbin/nss_exec
-chroot /mnt chown root:root /usr/bin/nvssh
-chroot /mnt chown root:root /etc/ssh/sshd_config
-chroot /mnt chown -R root:root /opt/forge/debs
-
-chroot /mnt groupadd --gid 959 nvssh-sudo-nopasswd
-chroot /mnt groupadd --gid 949 nvssh-sudo
-chroot /mnt groupadd ngc-automation
-chroot /mnt groupadd ngc
-chroot /mnt groupadd nsv
-chroot /mnt dpkg -R -i /opt/forge/debs
-
-#end nvinit setup
+  local forge_path_chroot_debs="${forge_path_debs#/mnt}"
+  ilog "=== Installing debs from $forge_path_chroot_debs: $(ls -la "$forge_path_debs"/*.deb)"
+  chroot /mnt chown -R root:root "$forge_path_chroot_debs"
+  chroot /mnt dpkg -R -i "$forge_path_chroot_debs" 2>&1 | while read -r log_line; do ilog "dpkg: $log_line"; done
 
 cat << \EOF > /mnt/var/lib/cloud/seed/nocloud-net/user-data
-#cloud-config
+# cloud-config
 timezone: "Etc/UTC"
 fqdn: {{ hostname }}
 manage_etc_hosts: true
 users:
-    # existing user left alone for now until forge user becomes used, then we can remove this entirely.
+  # The default `ubuntu` user left alone for now until forge user becomes used, then we can remove this entirely.
   - name: ubuntu
     shell: /bin/bash
     sudo: ALL=(ALL) NOPASSWD:ALL
@@ -167,13 +146,13 @@ write_files:
       #!/bin/bash
       function cleanup()
       {
-          CMD_PREFIX="ip vrf exec mgmt"
-          if [[ ! -f "/run/cloud-init.done" ]]
-          then
-            ${CMD_PREFIX} /opt/forge/forge-scout --api={{ api_url }} --machine-interface-id={{ interface_id }} --mode="standalone" logerror
-          else
-            /bin/rm /run/cloud-init.done
-          fi
+        CMD_PREFIX="ip vrf exec mgmt"
+        if [[ ! -f "/run/cloud-init.done" ]]
+        then
+          ${CMD_PREFIX} /opt/forge/forge-scout --api={{ api_url }} --machine-interface-id={{ interface_id }} --mode="standalone" logerror
+        else
+          /bin/rm /run/cloud-init.done
+        fi
       }
       trap cleanup EXIT
       set -e
@@ -182,7 +161,7 @@ write_files:
       /usr/bin/bfrec --capsule /lib/firmware/mellanox/boot/capsule/efi_sbkeysync.cap || true
       /usr/bin/bfcfg
       ip vrf exec mgmt curl --retry 5 --retry-all-errors -v -o /opt/forge/forge_root.pem {{ pxe_url }}/api/v0/tls/root_ca
-      echo "downloaded forge root cert"
+      echo "Downloaded Forge root cert"
       /usr/bin/mlxprivhost -d /dev/mst/mt*_pciconf0 r --disable_rshim --disable_tracer --disable_counter_rd --disable_port_owner
       bash -c '/usr/bin/mlxconfig -y -d /dev/mst/mt*_pciconf0 s SRIOV_EN=True NUM_OF_VFS=16 HIDE_PORT2_PF=True NUM_OF_PF=1'
       bash -c '/usr/bin/mlxconfig -y -d /dev/mst/mt*_pciconf0 set LINK_TYPE_P1=2 LINK_TYPE_P2=2' || true # not all BF2s have VPI so ignore the error if it does not
@@ -195,9 +174,8 @@ write_files:
       ctr -n=k8s.io image import /opt/forge/doca_hbn.tar
       /opt/mellanox/doca/services/telemetry/import_doca_telemetry.sh
 
-
       {% if forge_vf_intercept_bridge_name %}
-        
+
         # Create our new bridge
         ovs-vsctl --may-exist add-br {{ forge_vf_intercept_bridge_name }} -- set bridge {{ forge_vf_intercept_bridge_name }} datapath_type=netdev -- set interface {{ forge_vf_intercept_bridge_name }} mtu_request=9216
 
@@ -234,9 +212,9 @@ write_files:
 
         {% endif %}
       {% endif %}
-      
+
       {% if forge_host_intercept_bridge_name %}
-        
+
         # Create our new bridge
         ovs-vsctl --may-exist add-br {{ forge_host_intercept_bridge_name }} -- set bridge {{ forge_host_intercept_bridge_name }} datapath_type=netdev
 
@@ -268,7 +246,7 @@ write_files:
         {% endif %}
       {% endif %}
 
-      # Now restart sfc.  This might not be necessary since OVS restart seems
+      # Now restart sfc. This might not be necessary since OVS restart seems
       # to trigger this because of a systemd dependency.
       /usr/sbin/service sfc restart
 
@@ -278,23 +256,24 @@ write_files:
       /opt/forge/run-scout.sh
       touch /run/cloud-init.done
 
-# run these commands (last)
-runcmd:
-  - [ bash, -c, '/opt/forge/runcmds.sh' ]
-EOF
+  # Run these commands (last)
+  runcmd:
+    - [ bash, -c, '/opt/forge/runcmds.sh' ]
+  EOF
 
-ilog "======== End of bfb_modify_os ============"
-ilog "$(/usr/sbin/fdisk -l)"
-ilog "$(/usr/bin/lsblk)"
-ilog "$(/usr/sbin/blkid)"
-ilog "$(/usr/bin/efibootmgr -v)"
-ilog "==================================="
-ilog "==================================="
-# restore previous errexit behavior
-set +e
+  ilog "======== End of carbide_modify_os ============"
+  ilog "$(/usr/sbin/fdisk -l)"
+  ilog "$(/usr/bin/lsblk)"
+  ilog "$(/usr/sbin/blkid)"
+  ilog "$(/usr/bin/efibootmgr -v)"
+  ilog "==================================="
+  ilog "==================================="
+
+  # Restore previous errexit behavior
+  set +e
 }
 
-# This function is called by install.sh script embedded in the BFB
+# This function is called by install.sh script embedded in the BFB installer
 bfb_modify_os() {
   carbide_modify_os
 }
